import { Language } from '../types';

export const translations = {
  en: {
    title: "MirMag Gemini",
    subtitle: "A psychological mirror reflecting your soul through the lens of Tarot and Artificial Intelligence.",
    inputLabel: "Describe your state of mind",
    placeholder: "Share your thoughts, feelings, or a question seeking guidance...",
    buttonAnalyze: "Reveal Portrait",
    buttonClear: "Clear",
    analyzing: "Consulting the Oracle...",
    generating: "Manifesting Vision...",
    errorGeneric: "An unknown error occurred connecting to the mystical realm.",
    footer: "Powered by Google Gemini 2.5 Flash & 3 Pro Image",
    archetypeManifested: "Archetype Manifested",
    theRevelation: "The Revelation",
    generatedBy: "Generated by Gemini 3 Pro"
  },
  ru: {
    title: "MirMag Gemini",
    subtitle: "Психологическое зеркало, отражающее вашу душу через призму Таро и Искусственного Интеллекта.",
    inputLabel: "Опишите ваше состояние",
    placeholder: "Поделитесь мыслями, чувствами или вопросом, требующим ответа...",
    buttonAnalyze: "Раскрыть Портрет",
    buttonClear: "Очистить",
    analyzing: "Обращение к Оракулу...",
    generating: "Манифестация Видения...",
    errorGeneric: "Произошла неизвестная ошибка при связи с мистической сферой.",
    footer: "Работает на Google Gemini 2.5 Flash и 3 Pro Image",
    archetypeManifested: "Проявленный Архетип",
    theRevelation: "Откровение",
    generatedBy: "Сгенерировано Gemini 3 Pro"
  }
} as const;

export type TranslationKeys = typeof translations.en;
