import { Language } from '../types';

export const translations = {
  en: {
    title: "Gaze Into The Depths",
    subtitle: "A psychological mirror reflecting your soul through the lens of Tarot and Artificial Intelligence.",
    inputLabel: "Describe your state of mind",
    placeholder: "Share your thoughts, feelings, or a question seeking guidance...",
    buttonAnalyze: "Reveal Portrait",
    buttonClear: "Clear",
    analyzing: "Consulting the Oracle...", // Used for the combined loading state
    generating: "Manifesting Vision...", // Kept for type compatibility if needed
    errorGeneric: "An unknown error occurred connecting to the mystical realm.",
    footer: "Powered by Groq Llama 3.3 & OpenRouter Flux Pro",
    archetypeManifested: "Archetype Manifested",
    theRevelation: "The Revelation",
    generatedBy: "Generated by Flux 1.1 Pro"
  },
  ru: {
    title: "Загляни в глубину",
    subtitle: "Психологическое зеркало, отражающее вашу душу через призму Таро и Искусственного Интеллекта.",
    inputLabel: "Опишите ваше состояние",
    placeholder: "Поделитесь мыслями, чувствами или вопросом, требующим ответа...",
    buttonAnalyze: "Раскрыть Портрет",
    buttonClear: "Очистить",
    analyzing: "Обращение к Оракулу...", // Used for the combined loading state
    generating: "Манифестация Видения...", // Kept for type compatibility if needed
    errorGeneric: "Произошла неизвестная ошибка при связи с мистической сферой.",
    footer: "Работает на Groq Llama 3.3 и OpenRouter Flux Pro",
    archetypeManifested: "Проявленный Архетип",
    theRevelation: "Откровение",
    generatedBy: "Сгенерировано Flux 1.1 Pro"
  }
} as const;

export type TranslationKeys = typeof translations.en;